### ISSUE TITLE
map.fitBounds() with bearing does not fit the entire bounds

### ISSUE THREAD

**Issue by blahblahblah-** [mapbox/mapbox-gl-js#10064]
When `map.fitBounds(...)` is called with a bearing option passed in, it seems like the bearing is not taken into the account on calculating the appropriate zoom, resulting in part of the bounded area to not be in view.

**mapbox-gl-js version**: 1.12.0

**browser**: Chrome

### Steps to Trigger Behavior

 1. Create a bounded area with a list of coordinates
 2. Call `map.fitBounds(...)` with bearing option set

### Link to Demonstration

https://jsfiddle.net/_blahblahblah/k4vL6s5r/

### Expected Behavior

When clicking on the 'Fit to Line at 29º Bearing' button in the demo link, all 6 stations should be in view.

### Actual Behavior

Only 4 of the 6 stations are in view.

**Comment by karimnaaji** [comment]
Hello @blahblahblah- , I think this was fixed by https://github.com/mapbox/mapbox-gl-js/pull/9821, but is not yet released.

**Comment by blahblahblah-** [comment]
Hi @karimnaaji, I also tested with the latest `main` and I can still reproduce the issue.

**Comment by karimnaaji** [comment]
Ok thanks for confirming!

**Comment by pimhoogendoorn** [comment]
Hi @TannerPerrien it seems that your fix has been merged however, I can still reproduce it even in the latest version `2.14.1`. Is that correct?

**Comment by pahuta** [comment]
Checked on v.2.15.0, bug is not reproduced.
Updated demo: https://jsfiddle.net/q4d50L9h/

@mapbox/gl-js , please consider to close the issue.

**Comment by chrisnok** [comment]
If you change the demo to use bearing 135 instead of 29, you get an extra padding. Is there a workaround for this?

**Comment by P110** [comment]
Has anyone looked into this? Getting the same issue using different bearings, resulting in a lot of extra padding (assuming the padding isn't being rotated?)
