### ISSUE TITLE
Stretchable images inc. example not working in Mac OS Safari & Firefox, Chrome OK

### ISSUE THREAD

**Issue by ashleyclough** [mapbox/mapbox-gl-js#10180]
v2.0.0. Appears to work correctly in v1.12.0, broken in v1.13.0

https://docs.mapbox.com/mapbox-gl-js/example/add-image-stretchable/ and my maps using stretchable images display correctly in MacOS Chrome 87, marker images not visible in Safari 14.0.1 or Firefox 83.0. Dev consoles report invalid "stretchX", "stretchY" and "content" values, no errors in Chrome.

**Comment by andrewharvey** [comment]
Looks like the same issue I had at https://github.com/mapbox/mapbox-gl-js/pull/10119#issuecomment-741503586 but I could never replicate it into a standalone repro.

**Comment by smonadjemi** [comment]
Similar issue here, where the overlay image does not render on Firefox (v 83) and Safari (v 14.0.1), but works fine on Chrome (v 87).  
I have my own example where this is an issue, but I realized it occurs even on [the map from documentations](https://docs.mapbox.com/mapbox-gl-js/example/image-on-a-map/).

**Comment by mourner** [comment]
Confirmed! There's also an error in the console saying `Error: out of range source coordinates for image copy`. Will investigate, thanks for the report!

**Comment by mourner** [comment]
Should be fixed by #10230, included in the v2.0.1 coming out this week.

**Comment by malwoodsantoro** [comment]
@mourner I'm still seeing this issue using v2.1.1 in Firefox (86.0.1) and Safari (14.0.3) using [this example](https://docs.mapbox.com/mapbox-gl-js/example/add-image-stretchable/) - 

![image](https://user-images.githubusercontent.com/19801577/112218255-c04ae100-8be0-11eb-8cf0-390118c9c9a7.png)
![image](https://user-images.githubusercontent.com/19801577/112218351-d658a180-8be0-11eb-9b8f-fbaa266b2db0.png)

Related https://github.com/mapbox/mapbox-gl-js-docs/issues/453

**Comment by malwoodsantoro** [comment]
@mourner I'm still seeing this issue using v2.1.1 in Firefox (86.0.1) and Safari (14.0.3) using [this example](https://docs.mapbox.com/mapbox-gl-js/example/add-image-stretchable/) - 

![image](https://user-images.githubusercontent.com/19801577/112218255-c04ae100-8be0-11eb-8cf0-390118c9c9a7.png)
![image](https://user-images.githubusercontent.com/19801577/112218351-d658a180-8be0-11eb-9b8f-fbaa266b2db0.png)

Related https://github.com/mapbox/mapbox-gl-js-docs/issues/453

**Comment by malwoodsantoro** [comment]
@mourner I'm still seeing this issue using v2.1.1 in Firefox (86.0.1) and Safari (14.0.3) using [this example](https://docs.mapbox.com/mapbox-gl-js/example/add-image-stretchable/) - 

![image](https://user-images.githubusercontent.com/19801577/112218255-c04ae100-8be0-11eb-8cf0-390118c9c9a7.png)
![image](https://user-images.githubusercontent.com/19801577/112218351-d658a180-8be0-11eb-9b8f-fbaa266b2db0.png)

Related https://github.com/mapbox/mapbox-gl-js-docs/issues/453
