### ISSUE TITLE
iOS Simulator Safari crashes running on M1 Chip mac

### ISSUE THREAD

**Issue by OttyLab** [mapbox/mapbox-gl-js#10260]
**mapbox-gl-js version**:
v2.0.0 (did not check v1.13.x)

**browser**:
Safari on iOS simulator

### Steps to Trigger Behavior

 1. Launch any iOS simulator on **M1 Chip** mac
 2.Launch Safari on the simulator
 3.Access any site that uses Mapbox GL JS (e.g. https://docs.mapbox.com/mapbox-gl-js/example/mapbox-gl-geocoder-accept-coordinates/)

### Link to Demonstration

https://docs.mapbox.com/mapbox-gl-js/example/mapbox-gl-geocoder-accept-coordinates/

### Expected Behavior
Browser does not crash and can handle map

### Actual Behavior
Crash happens
![image](https://user-images.githubusercontent.com/13183117/103745986-b84cbd80-5043-11eb-8fb0-b4d09465281e.png)

**Comment by remotethings** [comment]
issue is the same with v1.12

**Comment by asheemmamoowala** [comment]
@remotethings or @OttyLab  could you please help us narrow the root cause here by providing more information on what you are seeing - a video capture would be great, but also does the page crash loading the map or after rendering a frame? Are there any messages in the dev console or diagnostics from the simulator?

Thanks!

**Comment by ansis** [comment]
Does Safari on an M1 outside of the simulator work?

**Comment by remotethings** [comment]
Yep safari on M1 works fine, issue is just in simulator (in all configurations tried)

@asheemmamoowala - nothing useful in the dev console (consistent with it being a memory issue). Video attached (not sure how to tell if its map load or frame render)

https://user-images.githubusercontent.com/33620680/104088636-3ab1c900-5260-11eb-9265-b95e38b5e65c.mov

**Comment by ansis** [comment]
My guess is that this would be a problem with the simulator, rather than mapbox-gl-js. Since this affects only the simulator there probably isn't anything we'll be able to do on our end.

**Comment by karimnaaji** [comment]
@remotethings it's also possible that there is an issue with the simulator on _any_ WebGL related pages. Could you try a few examples from https://threejs.org/examples/ and report on whether these work as expected?

**Comment by remotethings** [comment]
@karimnaaji just tested and the threejs example works (horrifically slow, but it does load)
![simulator_screenshot_94A8FB3B-F190-424F-B021-36E70D39FC35](https://user-images.githubusercontent.com/33620680/104344493-1e7a8a00-54f5-11eb-81ba-5cdf50c01c8c.png)

Another potentially interesting note (or reason to ignore this bug..): it works fine when using "run on this mac" with a cordova based app in xcode

**Comment by rikschennink** [comment]
I think there's an issue with WebGL performance on M1 simulator, experiencing the same problems with testing my WebGL powered products. Very slow (unusable) rendering.

**Comment by Manduro** [comment]
This issue seems to have been fixed in Xcode 13 beta 2, released on June 24, 2021.

**Comment by mourner** [comment]
Awesome! Let's close this then and hope it stays fixed in the 13 final too — it doesn't look like we can do anything to fix this on our side.

**Comment by davidstosik** [comment]
I understand this is an old issue, and chances are I won't get a reply, but I want to mention that although iOS15 and above simulators work well, I am still seeing the same problem with a simulator that runs iOS 14.5.
I am on macOS 12.5, with Xcode 14.1.
