### ISSUE TITLE
Transform css makes the map crash the whole page

### ISSUE THREAD

**Issue by jokeeras** [mapbox/mapbox-gl-js#12148]
We render a map on a slide that can be landscape or portrait. For portrait mode we don't have specific css but for landscape mode we add `transform: rotate(-90deg) translateX(X) translateY(Y);` and mapbox crashes the page with this.

**mapbox-gl-js version**: 2.8.1

**browser**: Chrome

### Steps to Trigger Behavior
 1. Open the CodeSandbox
 2. Page crashes

### Link to Demonstration
If you comment `transform: rotate(-90deg) translateX(-120px) translateY(-120px);` from App.scss then refresh the page the map renders. Now uncomment the css and see that it renders the map but if you hover over it is gonna throw an error `Invalid LngLat object: (NaN, NaN)`. After that refresh the page again and is gonna crash. 

So if we have the css when mapbox loads it crashes the page and if we add it after the map renders it throws an error.
[CodeSandbox](https://codesandbox.io/s/mapbox-crash-70vqzv?file=/src/App.scss)

### Expected Behavior
The map renders and works normally.

### Actual Behavior
The map crashes the page or throws an error.

**Comment by SnailBones** [comment]
This might be similar to https://github.com/mapbox/mapbox-gl-js/issues/11492

cc @avpeery

**Comment by RELNO** [comment]
I've reported a similar issue in [react-map-gl](https://github.com/visgl/react-map-gl/issues/1942), but it was notes [there](https://github.com/visgl/react-map-gl/issues/1942#issuecomment-1211473693) that this issue stems from the way mapbox-gl-js [currently handles transformations ](https://github.com/mapbox/mapbox-gl-js/blob/79af3b651218d93ec84bee774f7cb02a8aebabd1/src/ui/map.js#L2859-L2867).
Here's the original issue:

### Description

My app requires a map within a div that is transformed using `matrix3d` CSS transformer. 
  
<img width="570" alt="Screen Shot 2022-08-04 at 10 55 03 AM" src="https://user-images.githubusercontent.com/14296774/182794540-0be5a7ab-b08b-4992-809a-d457eccbbb77.png">

This was done before version 7 by transforming (`matrix3d`) a wrapping div around the map so that:
```
<div
      style={{
        transform:
          "matrix3d(0.7770456253, 0.0728373591, 0, 0.0000944713, -0.1763942931, 0.5033773233, 0, -0.0003884256, 0, 0, 1, 0, 136, 152, 0, 1)",
        height: "100vh"
      }}
    >
      <Map
        {...viewport}
        mapboxApiAccessToken={MAPBOX_TOKEN}
      />
    </div>
```

However, since version 7 the map object will freeze+crash the app, and the map itself will fail to load. Please see this in action in the attached CSB below. 

### Expected Behavior

Map can be transform3d as before.

### Steps to Reproduce

Please reproduce issue below by changing from version 6 to 7
<img width="125" alt="Screen Shot 2022-08-04 at 10 54 25 AM" src="https://user-images.githubusercontent.com/14296774/182794404-b3d4f19d-1481-4f7c-95ac-db1317951886.png">

https://codesandbox.io/s/mapbox-issues-with-matrix-transform-nctjvk?file=/src/index.js

### Environment

- Framework version:
- Map library: DeckGL ^8, react-map-gl ^7
- Browser:chrome/FF
- OS: macOS


### Logs

There are different logs, most of them from other comps that fail to render due the lag. Some logs show mapbox fails to load tiles, but this is not consistent.

**Comment by jokeeras** [comment]
Hello,
It seems that the bug crashing the whole page is fixed but now there are 2 new bugs.

1. When you hover over the map you get an: **Error Invalid LngLat object: (NaN, NaN)**. It's probably from the rotation of the map, the coordinates are not read correctly. This bug was introduces in version 2.2.0. If you change the version to 2.1.0 it doesn't happen and dragging the map works.
![hoverError](https://user-images.githubusercontent.com/46708612/234289910-03f53a0f-49d7-42c5-83d6-1efd20b6b17e.png)

2. The map is cropped, because the width&height are reversed inside the **canvas** element. As you can see the map has a width: 700px and height: 300px but inside the canvas element you can see they are reversed. This bug was introduces in version 2.5.0. If you change the version to 2.4.0 it doesn't happen and the maps renders correctly.
![1](https://user-images.githubusercontent.com/46708612/234292571-97fd2730-76d9-4fd1-b9d0-42f20fdbeaf1.png)
![2](https://user-images.githubusercontent.com/46708612/234292589-8a4e9a9e-1dc5-4bbd-95cc-5c0b3568a655.png)

**Comment by NitayMG** [comment]
![Image](https://github.com/user-attachments/assets/abde03d3-29b5-41b0-b4ca-362177ee2246)
Still crash
