### ISSUE TITLE
featuresAt offset

### ISSUE THREAD

**Issue by anandthakker** [mapbox/mapbox-gl-js#1274]
`featuresAt` is somehow offset from rendered symbol locations:
![mgl-featuresat-bug](https://cloud.githubusercontent.com/assets/4974151/8158240/541cb1ce-1329-11e5-8847-4ab4a95aba3b.gif)

Using `map.featuresAt(e.point, {radius: 10}, ...)`, where `e` is the `mousemove` event.

**Comment by ansis** [comment]
If you look closely while zooming it looks like the icons aren't centered around their data point. Does the style use `icon-translate` or `icon-offset` to move the rendered icon?

**Comment by peterqliu** [comment]
@anandthakker you can also visualize the bounds of each symbol via `map.collisionDebug=true`, to see if you're within the area

**Comment by anandthakker** [comment]
@ansis Nope, neither of those properties is set in the style.  I'll check @peterqliu's debug thing out and post if I find anything.

**Comment by anandthakker** [comment]
@ansis @peterqliu Here's what I see with that `collisionDebug` setting on: 
![offset](https://cloud.githubusercontent.com/assets/4974151/8188055/6a1d47d8-1421-11e5-8e51-b3d4a541765d.gif)

**Comment by anandthakker** [comment]
@ansis looked at this with me a few days back, and I think determined the issue is that `dot.sdf` sprite is not centered in its box.  I'd be happy to submit a fix to this, but I know absolutely nothing about how the sprites are built/parsed, so I'd need a nudge in the right direction...

**Comment by ansis** [comment]
Is there an offset on non-retina screens?

hmm, the sprite looks ok. The sdf dot in the 2x sprite has `"pixelRatio": 1`. I think SpriteAtlas doesn't properly handle icons with a pixel ratio of 1 in a 2x atlas.

I think https://github.com/mapbox/mapbox-gl-js/issues/1124 would fix it, but it might be easier to just make a sprite with a 2x dot.

**Comment by jfirebaugh** [comment]
@anandthakker Was this fixed by one of the extend or featuresAt related changes?

**Comment by anandthakker** [comment]
@jfirebaugh sorry, haven't been in this project recently.  I'll bump it to a more recent version and let you know soon

**Comment by anandthakker** [comment]
@ansis @jfirebaugh Still happening on 0.11.2, but only on retina screens.

**Comment by ansis** [comment]
I think this could be fixed by https://github.com/mapbox/mapbox-gl-js/pull/1919 and/or https://github.com/mapbox/mapbox-gl-js/pull/2224. Can you still reproduce this with v0.16.0?

**Comment by anandthakker** [comment]
@ansis In the project where I was reproducing this, I changed the icons to `circle`, so I don't have an immediate test case.

**Comment by ansis** [comment]
Alright, thanks. I haven't offsets anywhere else so I'll close this for now.
