### ISSUE TITLE
Fix poor queryFeatures precision on large viewports 

### ISSUE THREAD

**Issue by mycoboco** [mapbox/mapbox-gl-js#2279]
v0.15.0:
### Steps to Trigger Behavior
1. Open [the "Display a popup on click" example](https://www.mapbox.com/mapbox-gl-js/example/popup-on-click/) with Safari on iMac 5k
2. Enlarge the Safari window enough to cover the full screen
3. Try to click one of makers on the map
### Expected Behavior

Can click the marker and a related pop-up shows
### Actual Behavior

Cannot click markers. Actually the clickable position drifts from the marker as the screen size grows.

![capture](https://cloud.githubusercontent.com/assets/2888601/13838142/f419e732-ec54-11e5-871a-2ca879fe2550.jpg)

**Comment by lucaswoj** [comment]
This is probably due to some floating point error at high zoom levels on a large display, perhaps related to #1733.

**Comment by mourner** [comment]
Let's just change GeoJSONSource default to `18`. `14` is too low.

**Comment by mourner** [comment]
Should be fixed in master, can you confirm?

**Comment by mycoboco** [comment]
Unfortunately, still have the same problem with the master branch.

**Comment by mourner** [comment]
@mycoboco can you also try the branch here (it has a slightly different API though)? #2224

**Comment by mycoboco** [comment]
@mourner sorry for late response. I failed to build the branch with `npm install` (no problem with the master one). Can you give me a hint for that?

```
npm ERR! No compatible version found: prova@^2.1.2
npm ERR! Valid install targets:
npm ERR! 0.0.1-security
```

**Comment by ansis** [comment]
@mycoboco thanks for trying. The changes have now been merged into master and released as part of `v0.16.0`. Instructions for migrating from `featuresAt` to `queryRenderedFeatures` can be found here: https://github.com/mapbox/mapbox-gl-js/blob/master/CHANGELOG.md#breaking-changes

**Comment by mycoboco** [comment]
@ansis thanks for the information.

I successfully built `v0.16.0` and tested again; replaced `featuresAt` with `queryRenderedFeatrues` and `console.log`-ed its return value to see if the clickable position worked correctly. Sadly, the problem still exists.

When making Safari use the whole screen, the map displayed is distorted and I get the same result when I use Chrome with setting my iMac to use denser screen (that is, to have higher resolutions).

**Comment by jfirebaugh** [comment]
→ #5639
