### ISSUE TITLE
Fix unexpected results for zoom-and-property function

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-js#2827]
```
        "fill-color": {
          "property": "property",
          "stops": [
            [{"zoom": 0, "value": 0}, "rgba(255,0,0,1)"],
            [{"zoom": 0, "value": 1}, "rgba(0,255,0,1)"],
            [{"zoom": 0, "value": 2}, "rgba(0,0,255,1)"],
            [{"zoom": 1, "value": 0}, "rgba(255,0,0,0)"],
            [{"zoom": 1, "value": 1}, "rgba(0,255,0,0)"],
            [{"zoom": 1, "value": 2}, "rgba(0,0,255,0)"]
          ]
        }
```

At z=0.1, I'd expect these fills to be rendered with opacity 0.9. Instead they are rendered with 0 opacity (fully transparent).

**Comment by lucaswoj** [comment]
I can imagine improving our handling of zoom-and-property functions by moving more interpolation logic to the shader via #pragmas

**Comment by lucaswoj** [comment]
Fixed by https://github.com/mapbox/mapbox-gl-js/pull/2971

**Comment by jfirebaugh** [comment]
https://github.com/mapbox/mapbox-gl-test-suite/tree/master/render-tests/fill-opacity/zoom-and-property-function is still failing on gl-js `master`.
