### ISSUE TITLE
Fix unexpected results for fill-opacity property function

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-js#2828]
```
        "fill-opacity": {
          "property": "property",
          "stops": [
            [
              0,
              1
            ],
            [
              4,
              0
            ]
          ]
        }
```

For values `0`, `1`, and `2`, I'd expect the rendering to look like:

![image](https://cloud.githubusercontent.com/assets/98601/16636454/14595bf6-438d-11e6-87fd-5930263d72f3.png)

But instead it renders everything with opacity 0.

Possibly related to #2827.

**Comment by lucaswoj** [comment]
Fixed by #2971

**Comment by jfirebaugh** [comment]
https://github.com/mapbox/mapbox-gl-test-suite/tree/master/render-tests/fill-opacity/property-function is still failing on gl-js `master`.
