### ISSUE TITLE
Popup not displaying underneath the marker when no space above

### ISSUE THREAD

**Issue by felixn11** [mapbox/mapbox-gl-js#3234]
mapbox-gl-js version:0.23.0

### Steps to Trigger Behavior
1. Set some markers on the map (See link http://blockoperator-89086.onmodulus.net/#/ for an example)
2. Drag mouse over markers in the top section of the map

### Expected Behavior
There's no room for displaying the popup above the marker, so show it beneath the markers

### Actual Behavior
Popup is displayed above the marker and a part of the popup is not showed because there's no room left.

**Additional question:**
Is there a way to still show the popup when on mouseover the popup? In this way users have the possibility to click a link in the popup. Also see  http://blockoperator-89086.onmodulus.net/#/ for an example). 

Right now the popup is only displayed when the mouse is over the marker. 
I've followed this example https://www.mapbox.com/mapbox-gl-js/example/popup-on-hover/

**Comment by mourner** [comment]
Your provided example is broken in Chrome. Can you set up a minimal test case on something like JSFiddle?

**Comment by felixn11** [comment]
It's hard for me to replicate the problem and it's like it's happening the other way around in JSFiddle.
In the below JSFiddle example, for some marker popups there's no room beneath the marker but it's still showing it there.

https://jsfiddle.net/zwo52wa2/4/show/ (full screen)
https://jsfiddle.net/zwo52wa2/4/ (code)

The provided link isn't showing a broken map for me though.

**Comment by jfirebaugh** [comment]
Can you try the latest release, v0.24? I want to make sure this isn't #3136, which was fixed.

**Comment by felixn11** [comment]
Running the latest release right now and the issue is still occuring. 

This issue probably occurs when dynamically adding elements to the HTML of the popup after the setHTML function is called. See https://jsfiddle.net/zwo52wa2/14/ in the "map,on('mousemove'" event. 

In the last lines of this event I'm appending a Mapbox element to the popup. Seems like it's still using the size of the setHTML and not of elements append after this function. 

I'm trying to accomplish to once create a Mapbox element for the popups, add this element dynamically and setting the center coordinates of the Mapbox in the popup according to the marker position (last mentioned not in JSFiddle).

**Comment by jfirebaugh** [comment]
> This issue probably occurs when dynamically adding elements to the HTML of the popup after the setHTML function is called.

Yes, when using automatic anchoring, the anchor is calculated when one of the setters (`setLngLat`, `setHTML`, etc) is called. If you add content to the popup via DOM methods, there's no way for the popup to know that automatically.

You could force the anchor to be recalculated by calling `popup.setLngLat(popup.getLngLat())`, or use `setHTML`/`setDOMContent` exclusively to change the content.

Closing, since this isn't a bug in gl-js.
