### ISSUE TITLE
Fill-extrusions sometimes crash Chrome

### ISSUE THREAD

**Issue by stevage** [mapbox/mapbox-gl-js#3881]
**mapbox-gl-js version**:0.29.0 (although it was possibly easier to trigger with 0.28.0)

Chrome: 55.0.2883.95 (64-bit) (no special WebGL flags enabled)
OS: OSX 10.9.5

### Steps to Trigger Behavior

 1. View http://bl.ocks.org/stevage/b3d552dd9dafb351c13130b2629c5d44
 2. Hold the mouse button down and pan and rotate around in random directions for ~30 seconds.
 
### Actual Behavior
The window freezes. If you don't quickly close the tab, the whole browser freezes a few seconds later.

**Comment by kristfal** [comment]
Hey,

I've been experiencing performance degradation, but no crashes. Are you able to make it crash without the fill-extrusions? Does it only happen when you rotate / change pitch? 

If you are mainly experiencing this on rotates, I think the underlying issue is not fill extrusions but rather the same thing that is happening in #3856. 

I recorded a timeline from 30 seconds of pitch / rotate actions. When I stopped moving the map camera, the worker spent more than 2 seconds on `postMessage` for a `VectorTileWorkerSource.redoPlacement`. 

I'm guessing redoPlacement is clogging the workers, and if you don't stop moving to let it recover, it could cause your crash.

This is on macOS 10.12.2 on a 2,3 GHz i7 with 16GB RAM.


![skjermbilde 2017-01-03 09 06 56](https://cloud.githubusercontent.com/assets/5638107/21602506/e37ed1c8-d194-11e6-82de-79e30b5c4e61.png)

**Comment by pbabik** [comment]
I can reproduce this on Chrome for Android. The browser doesn't freeze, but it crashes with WebGL error instead.

**Comment by mourner** [comment]
> I'm guessing redoPlacement is clogging the workers, and if you don't stop moving to let it recover, it could cause your crash.

Thanks for the investigation @kristfal! This is very likely. Looks like the cause is the same as in #3856.

**Comment by stevage** [comment]
I'm not certain it's the same thing. In my case, I really don't see the "interaction starts to lag after a couple of seconds". The performance remains snappy and synchronised with the mouse movements. Every now and then there is a brief pause (maybe 0.25s) but it immediately resumes. Up until the moment where the window suddenly completely freezes.

I do notice that it's very dependent on zoom. If I zoom in (so not many buildings visible) I can't trigger it. Zooming out to the whole city, it happens within a few seconds.

**Comment by mourner** [comment]
@stevage are you able to crash any non-extrusion examples?

**Comment by stevage** [comment]
Not so far. Although, if I try really hard, I can make [this page](emscycletours.site44.com/routes/mapbox/web/index.html) stop drawing properly (no lines, and no new tiles) and get pretty sluggish.

**Comment by averas** [comment]
I also get the feeling that it is closely related to #3856. On my machine I get very similar behaviour as described in that thread. @stevage Have you tried if this is present in v0.26.0?

**Comment by averas** [comment]
@stevage Yes it id. It was the first version shipped with extrusion support, however the API/style-spec was changed in v0.27.0 so code/examples for later versions have to be adjusted for v0.26.0.

**Comment by mourner** [comment]
I suspect this was fixed by #3938, but let me know if it's not — I'll reopen the issue.

**Comment by stevage** [comment]
Very sorry to report that the crash still happens for me:

http://bl.ocks.org/stevage/75ee9f482e4a580aef63ba778a291bf4

**Comment by averas** [comment]
I am not able to reproduce any problem (lag or freeze)...

**Comment by mourner** [comment]
@stevage hmm, I cannot reproduce on Chrome 55 / OS X as well — rotating/pitching erratically for 1 minute, no lag or crash.

**Comment by stevage** [comment]
Hmm, definitely still happens for me. Especially when I zoom out and lower the camera. Anything I can do to help narrow in on the cause?

(For a bit of explanation as to why I care, we're going to be making some very public maps that heavily feature 3D buildings, so robustness is important...)

**Comment by averas** [comment]
@stevage Perhaps it's platform-specific, what hardware are you on? I'm on: 

MacBook Pro (Retina, 15-inch, Late 2013) 2.3GHz i7 / 16GB
NVIDIA GeForce GT 750M 2048 MB
Intel Iris Pro 1536 MB

MacOS 10.12.2
Chrome 55.0.2883.95

**Comment by stevage** [comment]
```
Retina, 15-inch, Mid 2014
Processor  2.2 GHz Intel Core i7
Memory  16 GB 1600 MHz DDR3
Graphics  Intel Iris Pro 1536 MB
Graphics  Intel Iris Pro 1536 MB
```

**Comment by stevage** [comment]
I guess an interesting test might be to create a repeating animation loop rather than random mouse movement, and see whether it crashes at the same point each time.

**Comment by averas** [comment]
@stevage I was going to suggest the same thing. Other reproduction attempts would be more meaningful as well.

**Comment by stevage** [comment]
Hooray, I have a repeatable crash!

https://bl.ocks.org/stevage/raw/b863ddd9364c7bf076413119215022fd

On my system, as soon as the first transition is complete (just after seeing the road label "Victoria Parade" get rendered), it freezes. 

Interestingly, when viewing the bl.ocks in non-fullscreen mode, it works fine:

https://bl.ocks.org/stevage/b863ddd9364c7bf076413119215022fd

This isn't a minimal repro case, but I have to say, working on examples that crash the browser isn't very much fun.

**Comment by stevage** [comment]
Ok, this is super interesting. It doesn't crash if:

*  the window is full-width but half-height
* the window is full-height but half-width

**Comment by mourner** [comment]
@stevage hmm, works fine for me on MBP Retina 15''. 😕

**Comment by stevage** [comment]
Cool, I'm not sure if that's a good thing or a bad thing. :)

If I'm the only person on the planet with this problem, great - we can safely use these 3D views in public maps.

If there are other people for whom this happens, but no one at Mapbox can reproduce it, not so good. :)

I'll try some CPU profiling (as per @kristfal).

**Comment by stevage** [comment]
A bit more info, from `chrome://gpu`. These messages appear just after the map freezes:

```
[1787:771:0207/092606.952262:ERROR:gles2_cmd_decoder.cc(16945)] : [.DisplayCompositor-0x7f8112e18a00]GL ERROR :GL_INVALID_OPERATION : glCreateAndConsumeTextureCHROMIUM: invalid mailbox name
[1787:771:0207/092606.952330:ERROR:gles2_cmd_decoder.cc(11694)] : [.DisplayCompositor-0x7f8112e18a00]GL ERROR :GL_INVALID_VALUE : glScheduleCALayerCHROMIUM: unsupported texture format
[1787:771:0207/092606.952772:ERROR:gles2_cmd_decoder.cc(16945)] : [.DisplayCompositor-0x7f8112e18a00]GL ERROR :GL_INVALID_OPERATION : glCreateAndConsumeTextureCHROMIUM: invalid mailbox name
[1787:771:0207/092606.952790:ERROR:gles2_cmd_decoder.cc(11694)] : [.DisplayCompositor-0x7f8112e18a00]GL ERROR :GL_INVALID_VALUE : glScheduleCALayerCHROMIUM: unsupported texture format
```

**Comment by stevage** [comment]
My full GPU settings: http://bl.ocks.org/stevage/raw/ee7387e9b184662d48bb28669610da96/

**Comment by stevage** [comment]
Ok, huge discovery - it doesn't happen when running in incognito mode. So there's a very good chance that the cause is a conflict with a Chrome plugin. I got that idea from [here](https://bugs.chromium.org/p/chromium/issues/detail?id=479299), which pointed the finger at Google Talk.

**Comment by stevage** [comment]
Sigh, scratch that. It still crashes, although less often (in my test case, it crashes after a complete loop, not at the first stop). Also, disabling all extensions isn't enough to make it not crash in non-incognito mode.

**Comment by stevage** [comment]
Ok, very happy to report that since upgrading to Sierra, it doesn't crash anymore.

So, you could probably close this as confined to very old version of OSX?

**Comment by mourner** [comment]
Great! Let's close for now and reopen if there are reports of this reproducing again.

**Comment by iegik** [comment]
Last gpu messages I have:
```
[27787:775:0913/012447.088262:WARNING:ipc_message_attachment_set.cc(49)] : MessageAttachmentSet destroyed with unconsumed attachments: 0/1
[27787:775:0913/012456.603351:ERROR:texture_manager.cc(2209)] : [.WebGL-0x7fde910adc00]GL ERROR :GL_INVALID_ENUM : glTexParameteri: param was GL_LINEAR_MIPMAP_LINEAR
[27787:775:0913/012522.525453:ERROR:gles2_cmd_decoder.cc(18047)] : [.BrowserCompositor-0x7fbbb4c51400]GL ERROR :GL_INVALID_OPERATION : glCreateAndConsumeTextureCHROMIUM: invalid mailbox name
[27787:775:0913/012522.525489:ERROR:gles2_cmd_decoder.cc(12520)] : [.BrowserCompositor-0x7fbbb4c51400]GL ERROR :GL_INVALID_VALUE : glScheduleCALayerCHROMIUM: unsupported texture format
[27787:775:0913/012522.527432:ERROR:gles2_cmd_decoder.cc(12520)] : [.BrowserCompositor-0x7fbbb4c51400]GL ERROR :GL_INVALID_VALUE : glScheduleCALayerCHROMIUM: unsupported texture format
[27787:775:0913/012523.131680:ERROR:texture_manager.cc(2209)] : [.WebGL-0x7fdbed030c00]GL ERROR :GL_INVALID_ENUM : glTexParameteri: param was GL_LINEAR_MIPMAP_LINEAR
[27787:775:0913/012550.135272:ERROR:gles2_cmd_decoder.cc(18047)] : [.BrowserCompositor-0x7fbbb4c51400]GL ERROR :GL_INVALID_OPERATION : glCreateAndConsumeTextureCHROMIUM: invalid mailbox name
[27787:775:0913/012550.135319:ERROR:gles2_cmd_decoder.cc(12520)] : [.BrowserCompositor-0x7fbbb4c51400]GL ERROR :GL_INVALID_VALUE : glScheduleCALayerCHROMIUM: unsupported texture format
```


Data exported | 2018-09-13T07:44:47.328Z
Chrome version | Chrome/69.0.3497.92
Operating system | Mac OS X 10.13.6
GPU0 | VENDOR = 0x8086 [Intel Inc.], DEVICE= 0x1926 [Intel(R) Iris(TM) Graphics 540] *ACTIVE*


Viz service display compositor is not enabled by default.
Disabled Features: viz_display_compositor
Skia renderer is not used by default.
Disabled Features: skia_renderer
Skia deferred display list is not used by default.
Disabled Features: skia_deferred_display_list
