### ISSUE TITLE
Security Error on WebWorker IE11 Win8.1

### ISSUE THREAD

**Issue by michelson** [mapbox/mapbox-gl-js#4358]
Hello , we have found some security issues on windows explorer 11.
the specific error is on the blob url initialization for web worker. The bug is [documented here. ](https://connect.microsoft.com/IE/feedback/details/801810/web-workers-from-blob-urls-in-ie-10-and-11), it seems to be a bug on previous versions of IE11. The problem is that the `mapboxgl.supported()` still returns true. So, I see two options ,   `mapboxgl.supported()` should return false or patch WebWorker initialization with an strategy similar to [https://github.com/parallel-js/parallel.js/pull/16/files](https://github.com/parallel-js/parallel.js/pull/16/files)

I think this is actually related with #2504

**Comment by michelson** [comment]
some references:

![image](https://cloud.githubusercontent.com/assets/11976/23521314/323d44f2-ff5d-11e6-9650-5d31fdef4064.png)

![image](https://cloud.githubusercontent.com/assets/11976/23521324/3c4ea242-ff5d-11e6-9767-6e32b5b32053.png)

**Comment by andrewharvey** [comment]
I don't think it's related to #2504, in that I was getting multiple "Unimplemented type: 3" errors because my version of IE11/specific set of windows patches had a broken gzip which meant that the pbf vector tiles weren't being uncompressed by the browser.

**Comment by michelson** [comment]
hi @andrewharvey, I know, it's not strictly related, but is related in the sense that mapboxgl.support() is returning true, but the map throws an error.
we indeed thought that the error we had was the #2504, but then with some debugging we realise that it was a Web Worker blob issue.

**Comment by fabiomcosta** [comment]
I just noticed the same issue.
Maps won't show up on IE11.

<img width="394" alt="screen shot 2017-04-12 at 3 34 00 pm" src="https://cloud.githubusercontent.com/assets/28530/24982260/7e84825a-1f95-11e7-933f-63afad86f004.png">

**Comment by anandthakker** [comment]
Since this issue is fixed in current versions, I think fixing `supported()` to correctly return `false` should be sufficient.

**Comment by droachrkn** [comment]
This issue has not been fixed. Using the latest map box GL, IE 11 still throws the same error. This is not related to anything within this chain or otherwise. "Security Error", debugger pauses on the WebWorker.
