### ISSUE TITLE
Cluster count not showing in all cluster circles in version 0.42.2

### ISSUE THREAD

**Issue by oswaldosalazar** [mapbox/mapbox-gl-js#5854]
I've been using mapobox-gl version 0.39.1. I had to upgrade to the latest (0.42.2) to test the heatmap type, but then some clusters were missing the points count.
After uninstalling the latest version and going back to 0.39.1, the cluster count appeared normally again.

**Comment by jfirebaugh** [comment]
Thanks for using Mapbox, and sorry to hear you're running into an issue. In order for us to diagnose this issue, we'll need to be able to reproduce it ourselves. Could you please create a minimal self-contained JSFiddle that demonstrates the issue?

**Comment by alekzvik** [comment]
I have a similar issue. I can reproduce it in `v0.42.2`, but it is gone in fresh `v0.43.0-beta.1`.
I am not sure I will be able to extract a useful example for jsfiddle, also not sure it is needed because it is fixed in new beta release.

**Comment by jfirebaugh** [comment]
We'll need a self-contained example to be able to diagnose this.

**Comment by oswaldosalazar** [comment]
Problem persisted with 0.43, but it went away when I added 
`"text-allow-overlap": true`
to the `layout` properties in the cluster count layer.
