### ISSUE TITLE
[regression] 0.44.0 map.queryRenderedFeatures() completely ignores symbols

### ISSUE THREAD

**Issue by mike-marcacci** [mapbox/mapbox-gl-js#6074]
Upon upgrading to 0.44.0, map.queryRenderedFeatures() fails to return any `symbol` layers that use GeoJSON sources specified in the second argument. I've gone through my layers' layout properties one-by-one to see if there is one particular trigger, and there doesn't seem to be.

Do note, though, that rarely map.queryRenderedFeatures *will* return a symbol layer, but after just another second of map interaction, stops again. Downgrading to 0.43.0 fixes this.

[VIEW SCREENCAST](https://youtu.be/QSMfCEOEnAA)

Check out #6075 for a screencast of "expected" behavior.

**Comment by pathmapper** [comment]
Running into the same issue with **overzoomed** vector tile sources hosted by Mapbox.

Steps to reproduce using this [jsfiddle](https://jsfiddle.net/5550r1mc/):

1. Hover over the green circle -> Properties are shown on the right side of the map (using the the queryRenderedFeatures API)

2. Zoom further in

3. Hover again over the green circle -> Properties are NOT shown on the right side of the map

Please note: 
Sometimes it is necessary to repeat steps 2 and 3 to reproduce.
Zoom extend of the used vector tileset for the point: z11-z12


![query_symbol](https://user-images.githubusercontent.com/20856381/35633383-5fe988f8-06a9-11e8-8b78-1722d603bebc.gif)

**Comment by anandthakker** [comment]
@mike-marcacci Thanks for reporting and for the screencast.  Is there any chance you'd be able to share a live page that reproduces the issue?  So far, I haven't managed to reproduce it locally. 
 (@pathmapper's jsfiddle above does reliably show an issue [thanks!], but it's not clear that it's the same as the one you're seeing)

**Comment by mike-marcacci** [comment]
Hi @anandthakker, thanks for the reply. I don't have anything live running this version (I'm just running the previous one instead), but I'll try to get a simplified working demo live today.

**Comment by anandthakker** [comment]
I believe the overzooming problem that [@pathmapper described above](https://github.com/mapbox/mapbox-gl-js/issues/6074#issuecomment-361981622) happens like so:

- [render frame 1] Map starts at z12, so initial symbol placement occurs using tile `12/1283/1587`.

- Zoom to z13; this means that we have a new, overzoomed version of the above tile (`13/1283/1587` in the debug view)

- [render frame 2] We start a new placement, but it gets paused. Thus this code updating `map.style.collisionIndex` doesn't run: https://github.com/mapbox/mapbox-gl-js/blob/de593c852b7e11f976a6ab78856dedc950f370a5/src/style/style.js#L991-L999

- (btw, there might be some other issue at play here: it's not clear why we'd ever have to pause placement when we're only placing a _single_ symbol, as in this example)

 - [render frame 3] We continue the paused placement, and complete it.  However, since the `crossTileSymbolIndex` got [updated](https://github.com/mapbox/mapbox-gl-js/blob/de593c852b7e11f976a6ab78856dedc950f370a5/src/style/style.js#L961-L975) in the previous frame, `symbolBucketsChanged` is false this time.  And (I think?) because we're placing the same symbol again this time, [`placementChanged`](https://github.com/mapbox/mapbox-gl-js/blob/de593c852b7e11f976a6ab78856dedc950f370a5/src/style/style.js#L993) also comes back false.  As a result, we _still_ don't update `map.style.collisionIndex`.

The consequence: even though `map.style.sourceCache` is now operating off of the overzoomed (`13/1283/1587`) tile, the feature entry in `map.style.collisionIndex` refers to the original (`12/1283/1587`) tile, and thus gets filtered out of the query results.

cc @ansis @ChrisLoer

**Comment by anandthakker** [comment]
@mike-marcacci I'd be curios to know if this branch still exhibits the problem for you: https://github.com/mapbox/mapbox-gl-js/pull/6104

**Comment by mike-marcacci** [comment]
Hey there, so sorry for the delay; I haven’t had any cell service here and am just trying to get this out on 1 bar 😑. I will try with that branch as soon as I can download it!! Thanks so much for the super fast response here.

**Comment by mike-marcacci** [comment]
Hey team, sorry again for the delay – finally back on the grid. I can confirm that the branch 6074 (from PR #6104) restores the behavior from 0.43.0! Thanks for the quick fix!

**Comment by anandthakker** [comment]
Thanks for confirming, @mike-marcacci

**Comment by anandthakker** [comment]
Fixed in #6104

**Comment by gmaclennan** [comment]
@anandthakker I am still seeing this bug in 0.44.1. Returning to 0.43.0 works. Live example here: https://wherewework.amazonfrontlines.org/ source code: https://github.com/digidem/alianza-ceibo-maps/

**Comment by anandthakker** [comment]
Thanks @gmaclennan.  I suspect this might be a different underlying issue, but it's hard to be sure without a minimal reproduction -- could you either describe the details of the querying that's happening in your example or reduce it to a smaller example free of extraneous application code?

**Comment by gmaclennan** [comment]
Hey @anandthakker thanks for the quick response. This looks like it was a weird caching issue both on the published version and on my local dev machine, which means that the update to 0.44.1 was not coming through correctly. Anyhow, it seems to have started working again now.
