### ISSUE TITLE
Precision issues with Custom Style Layers

### ISSUE THREAD

**Issue by measuredweighed** [mapbox/mapbox-gl-js#7268]
I've been experimenting with @ansis' recently merged [Custom Style Layers](https://github.com/mapbox/mapbox-gl-js/commit/f556bee30d36d1001825f18734eda723b1174209). They're a great addition, but I've noticed what looks to be jitter at high zoom levels due to (I presume) floating point precision issues.

This can be seen in the provided `custom-style-layer.html` example. Simply zoom into the red quad (>= 16 zoom) and you'll notice it starts to jitter as the zoom level increases.

![2018-09-12_11-40-56](https://user-images.githubusercontent.com/1234600/45420167-5f420a00-b681-11e8-844d-31f7714290c3.gif)

If this is indeed a precision issue are there plans to mitigate this? I've seen [faked double precision](http://github.prideout.net/emulating-double-precision) (sometimes referred to as relative-to-eye rendering) used to mitigate similar issues in the past.

I'd be interested to hear if this is something you guys are hoping to address, or if you have any suggestions as to how best to work around the issue for the time being.

**Comment by measuredweighed** [comment]
@ansis Thanks for getting back to me so promptly! We are indeed looking for a global layer with high precision - which is part of the reason why I was confident this might be precision related (as we've run into similar issues in the past).

I took a run at augmenting the custom-style-layer example to support a version of relative-to-eye rendering (where we basically adjust the matrix provided to centre the eye at `0,0,0` and then use faked double precision in the vertex shader to render relative to the current map center).

The code is a little rough, but it does seem to work nicely in testing (I've moved null island to London's Heathrow airport for this test as the jitter is easier to detect over land). 

I'd be interested in helping to nail down a generic solution, as this is something we're keen to use in production.

```<div id='map'></div>
<script>
var map = window.map = new mapboxgl.Map({
    container: 'map',
    zoom: 10,
    center: [-0.454295, 51.470020],
    style: 'mapbox://styles/mapbox/light-v9',
    hash: true
});

var nullIslandLayer = {
    id: 'null-island',
    type: 'custom',

    onAdd: function (map, gl) {
        var vertexSource = "" +
        "uniform mat4 u_matrix;" +
        "uniform vec2 u_cameraPosHigh;" +
        "uniform vec2 u_cameraPosLow;" +
        "uniform vec2 u_nullIslandPosHigh;" +
        "uniform vec2 u_nullIslandPosLow;" +

        "vec2 translateRelativeToEye(vec2 high, vec2 low) {" +
        "   vec2 highDiff = high - u_cameraPosHigh;" +
        "   vec2 lowDiff = low - u_cameraPosLow;" +
        "   return highDiff + lowDiff;" +
        "}" +

        "void main() {" +
        "   vec2 pos = translateRelativeToEye(u_nullIslandPosHigh, u_nullIslandPosLow);" +
        "   gl_Position = u_matrix * vec4(pos, 0.0, 1.0);" +
        "   gl_PointSize = 25.0;" +
        "}";

        var fragmentSource = "" +
        "void main() {" +
        "    gl_FragColor = vec4(1.0, 0.0, 0.0, 1.0);" +
        "}";

        var vertexShader = gl.createShader(gl.VERTEX_SHADER);
        gl.shaderSource(vertexShader, vertexSource);
        gl.compileShader(vertexShader);
        var fragmentShader = gl.createShader(gl.FRAGMENT_SHADER);
        gl.shaderSource(fragmentShader, fragmentSource);
        gl.compileShader(fragmentShader);

    var error = gl.getShaderInfoLog(vertexShader);
    if(error.length > 0) console.log(error);
        this.program = gl.createProgram();
        gl.attachShader(this.program, vertexShader);
        gl.attachShader(this.program, fragmentShader);
        gl.linkProgram(this.program);
    },

    encodeFloatToDouble: function(value, array) {
        let result = new Float32Array(2);
        result[0] = value;
        
        let delta = value - result[0];
        result[1] = delta;
        return result;
    },
    lngLatToMercator: function (lngLat) {
        // derived from https://gist.github.com/springmeyer/871897
        var extent = 20037508.34;
    
        var x = lngLat.lng * extent / 180;
        var y = Math.log(Math.tan((90 + lngLat.lat) * Math.PI / 360)) / (Math.PI / 180);
        y = y * extent / 180;
    
        return {
            x: (x + extent) / (2 * extent),
            y: 1 - ((y + extent) / (2 * extent))
        };
    },

    render: function(gl, matrix) {

        // Create an RTE matrix that positions the camera at 0, 0, 0
        var relativeToEyeMatrix = [
            matrix[0], matrix[1], matrix[2], matrix[3],
            matrix[4], matrix[5], matrix[6], matrix[7],
            matrix[8], matrix[9], matrix[10], matrix[11],
            0, 0, 0, matrix[15]
        ];

        // Convert our map center to mercator meters [0 .. 1]
        var cameraPosMeters = this.lngLatToMercator(map.transform._center);

        // Encode our camera position to fake doubles
        var cameraPosX = this.encodeFloatToDouble(cameraPosMeters.x);
        var cameraPosY = this.encodeFloatToDouble(cameraPosMeters.y);

        // Encode our null island position to fake doubles
        var nullIslandPosMeters = this.lngLatToMercator(new mapboxgl.LngLat(-0.454295, 51.470020));
        var nullIslandPosX = this.encodeFloatToDouble(nullIslandPosMeters.x);
        var nullIslandPosY = this.encodeFloatToDouble(nullIslandPosMeters.y);

        gl.useProgram(this.program);
        gl.uniformMatrix4fv(gl.getUniformLocation(this.program, "u_matrix"), false, relativeToEyeMatrix);
        gl.uniform2f(gl.getUniformLocation(this.program, "u_cameraPosHigh"), cameraPosX[0], cameraPosY[0]);
        gl.uniform2f(gl.getUniformLocation(this.program, "u_cameraPosLow"), cameraPosX[1], cameraPosY[1]);

        gl.uniform2f(gl.getUniformLocation(this.program, "u_nullIslandPosHigh"), nullIslandPosX[0], nullIslandPosY[0]);
        gl.uniform2f(gl.getUniformLocation(this.program, "u_nullIslandPosLow"), nullIslandPosX[1], nullIslandPosY[1]);

        gl.drawArrays(gl.POINTS, 0, 1);
    }
};

map.on('load', function() {
    map.addLayer(nullIslandLayer);
});
</script>

**Comment by lileialg** [comment]
@measuredweighed###  I really appreciate that

**Comment by lileialg** [comment]
@measuredweighed When I rotate the map, the position of the point is wrong,Do you have any other method?

**Comment by peterqliu** [comment]
@lileialg @measuredweighed check out https://github.com/peterqliu/threebox for a third-party library connecting three.js to mapboxgl. It addresses many of the camera precision and coordinate issues that are common to this task

**Comment by lileialg** [comment]
@peterqliu I convert position to pixel in javascript instead of in shader script,It looks like working fine,But much more calculation in javascript.
[custom3d-13.txt](https://github.com/mapbox/mapbox-gl-js/files/2538115/custom3d-13.txt)

**Comment by herewaitting** [comment]
> @ansis Thanks for getting back to me so promptly! We are indeed looking for a global layer with high precision - which is part of the reason why I was confident this might be precision related (as we've run into similar issues in the past).
> 
> I took a run at augmenting the custom-style-layer example to support a version of relative-to-eye rendering (where we basically adjust the matrix provided to centre the eye at `0,0,0` and then use faked double precision in the vertex shader to render relative to the current map center).
> 
> The code is a little rough, but it does seem to work nicely in testing (I've moved null island to London's Heathrow airport for this test as the jitter is easier to detect over land).
> 
> I'd be interested in helping to nail down a generic solution, as this is something we're keen to use in production.
> 
> ```
> <script>
> var map = window.map = new mapboxgl.Map({
>     container: 'map',
>     zoom: 10,
>     center: [-0.454295, 51.470020],
>     style: 'mapbox://styles/mapbox/light-v9',
>     hash: true
> });
> 
> var nullIslandLayer = {
>     id: 'null-island',
>     type: 'custom',
> 
>     onAdd: function (map, gl) {
>         var vertexSource = "" +
>         "uniform mat4 u_matrix;" +
>         "uniform vec2 u_cameraPosHigh;" +
>         "uniform vec2 u_cameraPosLow;" +
>         "uniform vec2 u_nullIslandPosHigh;" +
>         "uniform vec2 u_nullIslandPosLow;" +
> 
>         "vec2 translateRelativeToEye(vec2 high, vec2 low) {" +
>         "   vec2 highDiff = high - u_cameraPosHigh;" +
>         "   vec2 lowDiff = low - u_cameraPosLow;" +
>         "   return highDiff + lowDiff;" +
>         "}" +
> 
>         "void main() {" +
>         "   vec2 pos = translateRelativeToEye(u_nullIslandPosHigh, u_nullIslandPosLow);" +
>         "   gl_Position = u_matrix * vec4(pos, 0.0, 1.0);" +
>         "   gl_PointSize = 25.0;" +
>         "}";
> 
>         var fragmentSource = "" +
>         "void main() {" +
>         "    gl_FragColor = vec4(1.0, 0.0, 0.0, 1.0);" +
>         "}";
> 
>         var vertexShader = gl.createShader(gl.VERTEX_SHADER);
>         gl.shaderSource(vertexShader, vertexSource);
>         gl.compileShader(vertexShader);
>         var fragmentShader = gl.createShader(gl.FRAGMENT_SHADER);
>         gl.shaderSource(fragmentShader, fragmentSource);
>         gl.compileShader(fragmentShader);
> 
>     var error = gl.getShaderInfoLog(vertexShader);
>     if(error.length > 0) console.log(error);
>         this.program = gl.createProgram();
>         gl.attachShader(this.program, vertexShader);
>         gl.attachShader(this.program, fragmentShader);
>         gl.linkProgram(this.program);
>     },
> 
>     encodeFloatToDouble: function(value, array) {
>         let result = new Float32Array(2);
>         result[0] = value;
>         
>         let delta = value - result[0];
>         result[1] = delta;
>         return result;
>     },
>     lngLatToMercator: function (lngLat) {
>         // derived from https://gist.github.com/springmeyer/871897
>         var extent = 20037508.34;
>     
>         var x = lngLat.lng * extent / 180;
>         var y = Math.log(Math.tan((90 + lngLat.lat) * Math.PI / 360)) / (Math.PI / 180);
>         y = y * extent / 180;
>     
>         return {
>             x: (x + extent) / (2 * extent),
>             y: 1 - ((y + extent) / (2 * extent))
>         };
>     },
> 
>     render: function(gl, matrix) {
> 
>         // Create an RTE matrix that positions the camera at 0, 0, 0
>         var relativeToEyeMatrix = [
>             matrix[0], matrix[1], matrix[2], matrix[3],
>             matrix[4], matrix[5], matrix[6], matrix[7],
>             matrix[8], matrix[9], matrix[10], matrix[11],
>             0, 0, 0, matrix[15]
>         ];
> 
>         // Convert our map center to mercator meters [0 .. 1]
>         var cameraPosMeters = this.lngLatToMercator(map.transform._center);
> 
>         // Encode our camera position to fake doubles
>         var cameraPosX = this.encodeFloatToDouble(cameraPosMeters.x);
>         var cameraPosY = this.encodeFloatToDouble(cameraPosMeters.y);
> 
>         // Encode our null island position to fake doubles
>         var nullIslandPosMeters = this.lngLatToMercator(new mapboxgl.LngLat(-0.454295, 51.470020));
>         var nullIslandPosX = this.encodeFloatToDouble(nullIslandPosMeters.x);
>         var nullIslandPosY = this.encodeFloatToDouble(nullIslandPosMeters.y);
> 
>         gl.useProgram(this.program);
>         gl.uniformMatrix4fv(gl.getUniformLocation(this.program, "u_matrix"), false, relativeToEyeMatrix);
>         gl.uniform2f(gl.getUniformLocation(this.program, "u_cameraPosHigh"), cameraPosX[0], cameraPosY[0]);
>         gl.uniform2f(gl.getUniformLocation(this.program, "u_cameraPosLow"), cameraPosX[1], cameraPosY[1]);
> 
>         gl.uniform2f(gl.getUniformLocation(this.program, "u_nullIslandPosHigh"), nullIslandPosX[0], nullIslandPosY[0]);
>         gl.uniform2f(gl.getUniformLocation(this.program, "u_nullIslandPosLow"), nullIslandPosX[1], nullIslandPosY[1]);
> 
>         gl.drawArrays(gl.POINTS, 0, 1);
>     }
> };
> 
> map.on('load', function() {
>     map.addLayer(nullIslandLayer);
> });
> </script>
> ```

Hi,
I used your method to solve the problem of accuracy, but at the same time another problem arises. The orientation of the camera can only be perpendicular to the map. Otherwise, the drawing layer will not be seen. How to solve this problem at this time?
Thanks

**Comment by measuredweighed** [comment]
@herewaitting This is down to me only encoding the `x` and `y` coordinates in the example. Since this was written @ansis has implemented a really handy `[MercatorCoordinate](https://docs.mapbox.com/mapbox-gl-js/api/#mercatorcoordinate)` helper that can convert from `LngLnt` => GL coordinates. So I'd recommend using those and encoding all 3 axis.

**Comment by herewaitting** [comment]
> @measuredweighed是的，这是一个精确的问题！谢谢你打开这个问题。
> 
> 在内部，我们通过将坐标存储在更局部的坐标空间中并将矩阵转换为与该坐标空间一起工作来避免这种精度问题。在转换矩阵时，在js中完成高精度数学运算。
> 
> 该threejs例子做到这一点[在这里](https://github.com/mapbox/mapbox-gl-js/blob/bb5806e2b5996dcebf006e9b0334255c5acb4db9/debug/threejs.html#L70-L71)。
> 
> 如果渲染的所有内容非常接近，这种方法非常简单。如果您需要具有高精度的全局图层，则需要使用此方法实现某种类型的平铺。这可能变得复杂。
> 
> 我想我们可能希望为帮助创建这些矩阵添加某种支持。如果您认为这种方法对您有用，那么听一下添加来解决这个问题会有所帮助。
> 
> > 如果这确实是一个精确的问题，是否有计划减轻这种情况？我曾经看到伪造的双精度（有时称为相对于眼睛的渲染）用于缓解过去的类似问题。
> 
> 是的。我个人没有这种方法的经验，但可以将它与矩阵一起使用。我认为用矩阵投影位置时你可以做假双精度数学吗？

Where is the internal processing code?

**Comment by herewaitting** [comment]
@ansis   

Where is the internal processing code?

**Comment by ansis** [comment]
> I used your method to solve the problem of accuracy, but at the same time another problem arises. The orientation of the camera can only be perpendicular to the map. Otherwise, the drawing layer will not be seen. How to solve this problem at this time?

@herewaitting I think this should also work when the map is tilted:
```js
       // this goes within `render`
        var centerCoord = mapboxgl.MercatorCoordinate.fromLngLat(map.getCenter());
        var r = matrix.slice(); // copy the matrix;
        // translate the matrix by the center coord
        r[12] += r[0] * centerCoord.x + r[4] * centerCoord.y;
        r[13] += r[1] * centerCoord.x + r[5] * centerCoord.y;
        r[14] += r[2] * centerCoord.x + r[6] * centerCoord.y;
        r[15] += r[3] * centerCoord.x + r[7] * centerCoord.y;
        var relativeToEyeMatrix = r;
```

@measuredweighed thanks again for the original implementation!

**Comment by herewaitting** [comment]
> > I used your method to solve the problem of accuracy, but at the same time another problem arises. The orientation of the camera can only be perpendicular to the map. Otherwise, the drawing layer will not be seen. How to solve this problem at this time?
> 
> @herewaitting I think this should also work when the map is tilted:
> 
> ```js
>        // this goes within `render`
>         var centerCoord = mapboxgl.MercatorCoordinate.fromLngLat(map.getCenter());
>         var r = matrix.slice(); // copy the matrix;
>         // translate the matrix by the center coord
>         r[12] += r[0] * centerCoord.x + r[4] * centerCoord.y;
>         r[13] += r[1] * centerCoord.x + r[5] * centerCoord.y;
>         r[14] += r[2] * centerCoord.x + r[6] * centerCoord.y;
>         r[15] += r[3] * centerCoord.x + r[7] * centerCoord.y;
>         var relativeToEyeMatrix = r;
> ```
> 
> @measuredweighed thanks again for the original implementation!

Thank you very much for solving the problem thoroughly, and I hope you can explain why changing matrix 12/13/14/15 can solve the problem.

**Comment by ansis** [comment]
`centerCoord` is the coordinate of the center of the map in the same coordinate space that the map uses. If you project `centerCoord` using the matrix you'll end up putting something at the center of the map. Our goal is change the matrix so that the coordinate `[0, 0]` gets put at the center of the map. We do this by translating the matrix by `centerCoord`. Using a method like [glmatrix's translate](http://glmatrix.net/docs/module-mat4.html) would be a clearer way of doing this:

```mat4.translate(matrix, matrix, [centerCoord.x, centerCoord.y, 0, 0])```

Those four lines are just extracted from that code: http://glmatrix.net/docs/mat4.js.html#line405

Googling "matrix translation" might provide more background on how that math works.

**Comment by mourner** [comment]
Looks like this is sufficiently resolved with the current [MercatorCoordinate](https://docs.mapbox.com/mapbox-gl-js/api/#mercatorcoordinate) API, and there are no obvious next actions, so I'm closing for now.

**Comment by mourner** [comment]
Also see #8709 for a related discussion.

**Comment by fr-an-k** [comment]
MeractorCoordinate API does not resolve anything for this issue?
