### ISSUE TITLE
iOS Safari Console Error 'Unhandled Promise Rejection: AbortError: Fetch is aborted'

### ISSUE THREAD

**Issue by nbertrand-bh** [mapbox/mapbox-gl-js#8480]
**mapbox-gl-js version**: 1.1.0

**browser**: iOS Safari on iOS 12.3.1

### Steps to Trigger Behavior

 1. Load up a map on iOS Safari:  https://docs.mapbox.com/mapbox-gl-js/example/simple-map/
 2. Start scrolling around, pinch/zoom, etc.
 3. Error will pop up on the aborted fetch. 

### Link to Demonstration

https://docs.mapbox.com/mapbox-gl-js/example/simple-map/

### Expected Behavior

We recently upgraded our maps from 0.53.1 to 1.1.0. Prior to our upgrade, these errors were not logging in Bugsnag. I also fired up a branch right before we upgraded and was not able to get the error to log into the console. The map continues to work normally even with these errors. 

Expected behavior is for these errors to not be logged to the console. 

### Actual Behavior

Error is thrown into console. 
This is the console from 
<img width="1001" alt="Screen Shot 2019-07-15 at 10 47 49 AM" src="https://user-images.githubusercontent.com/45976175/61230696-2aaf3c80-a6f0-11e9-8244-e5a47e3cb3d2.png">

**Comment by ryanhamley** [comment]
I'm having trouble recreating this error. Does it happen every time? How long does it usually take to create the error? I'm also using Safari on iOS 12.3.1.

**Comment by nbertrand-bh** [comment]
It doesn't happen every time. Doing some more testing it seemed to happen more if I zoom out to US level then zoom in quickly to a new part of the map. I was just able to re-create it 7/10 times on the example simple map. 

Some possible good news, I went back and checked our bugsnag and saw it was also happening on OSX safari. So I went to test it and it was very easily recreated there. 

![MapboxFetchError](https://user-images.githubusercontent.com/45976175/61303148-a7075580-a7ac-11e9-81b4-4f9261b70994.gif)

**Comment by hulsizer** [comment]
@ryanhamley Any update on this?

**Comment by ryanhamley** [comment]
Hi @hulsizer and @nbertrand-bh thanks for your patience. I took a look at this and my initial diagnosis is that this may be related to a [known Safari bug](https://bugs.webkit.org/show_bug.cgi?id=174980#c2) in which `Fetch.abortController` is implemented in Safari but doesn't actually do anything in certain versions. I'm not sure there's much we can do here but the good news is that this seems to be fairly harmless.

**Comment by nbertrand-bh** [comment]
Just a heads up. We just updated to the latest version (1.6.0) and it's still showing up. Don't need to re-open it, and we're just going to permanently mute the bugsnag error for this since it does appear harmless.

**Comment by malwoodsantoro** [comment]
Reopening this issue as I've been able to reproduce it using v1.6.0. I used a simple example (see https://jsfiddle.net/scLqt0o3/) and panned in and out very quickly several times until the error appeared. 

![image](https://user-images.githubusercontent.com/19801577/72858179-cbb91a00-3c74-11ea-8fa4-2d36a1c76e16.png)

**Safari v13.0.4
Mapbox v1.6.1**

**Comment by Plantain** [comment]
We are seeing thousands of these in the wild every day, almost all from iOS/Safari.

**Comment by jpopham** [comment]
Also getting them in Mac/Safari

**Comment by katydecorah** [comment]
The Docs team's Sentry alerted this issue as well. 

You can reproduce by zooming in and out of this map in Safari (Version 13.0.5 (15608.5.11)): https://docs.mapbox.com/studio-manual/examples/hillshade/

**Comment by erinmeyers88** [comment]
Hello, I am also experiencing this issue. 

Browsers: Safari 14 on Catalina 10.15.7 and Safari on iOS 13.7 

I encounter the issue when zooming in/out quickly.  It seems to occur much more frequently when the hillshade layer is turned on and causes my app to freeze temporarily.  Without the hillshade layer, the issue occurs less frequently and it doesn't seem to affect the user experience.

**Comment by kcoyner** [comment]
I am also seeing this issue.

Safari on iOS 14.2.

**Comment by asheemmamoowala** [comment]
Looks like a bug in Safari/Webkit: https://bugs.webkit.org/show_bug.cgi?id=215771

**Comment by themumy10** [comment]
Any updates on issue?

**Comment by richigonzalez** [comment]
Any update?

**Comment by src01001100** [comment]
Same here. This needs to be attacked.

**Comment by ulilopezpacho** [comment]
I'm also having the same problem. Any news?

**Comment by vjohnston** [comment]
+1, also facing this issue! Any updates? It seems like many people here would really appreciate a fix 🙏

**Comment by avpeery** [comment]
@vjohnston Thanks for using Mapbox! From the previous discussion, it looks like the problem was determined to be a [harmless bug caused by webkit](https://github.com/mapbox/mapbox-gl-js/issues/10498#issuecomment-805151951) Can you elaborate what the error is on your end and how it's impacting your map experience? It would be a great help to include a minimal code reproduction, and include what version of GL JS you are using.

**Comment by jschaf** [comment]
WebKit merged a [PR](https://github.com/WebKit/WebKit/pull/11864) on March 23 that closed the linked bugs.

https://bugs.webkit.org/show_bug.cgi?id=215771
https://bugs.webkit.org/show_bug.cgi?id=251463

**Comment by stepankuzmin** [comment]
Closing the issue since it was resolved in the WebKit upstream.

**Comment by dongdong-wu1001** [comment]
The error still exist on Safari mobile(16.1)/desktop(16.5), mapbox version: 2.15.

The errors captures on Datadog RUM - `AbortError: Fetch is aborted`
