### ISSUE TITLE
Regression in WorkerTile on sourceLayers lookup

### ISSUE THREAD

**Issue by fnicollet** [mapbox/mapbox-gl-js#913]
Hello,

I just updated to the very last version of the repo ( @mourner commits took 25k off the final dev size with the PBF changes, good one!) but unfortunately, code that was working before no longer works.
I am using mapbox-gl-js in IE with bright-v6.json.

I believe this comes from this commit by @lbud , probably this one:
https://github.com/mapbox/mapbox-gl-js/commit/2ca21d5a637c7f768539730f736ebc907deb24b4
Because the error happens in some code that was introduced in this commit.
Basically at this line:
https://github.com/mapbox/mapbox-gl-js/blob/2f334b8df8c47e4bb5302de8393cea1f8b6ff2a2/js/source/worker_tile.js#L194

sourceLayers[l.ref] is undefined so the second [l.ref] lookup fails.
In this case, "l" has an id of "tunnel_motorway_link" and a ref equals to "tunnel_motorway_link_casing".
While sourceLayers contains this:
![image](https://cloud.githubusercontent.com/assets/1240481/5637902/bc5dbe82-9600-11e4-931d-0f416ac0280e.png)

I am not sure how this should be fixed, could you please have a look?

Thanks,
Fabien

**Comment by lbud** [comment]
Hey @fnicollet, regarding the first issue, I just pushed a different fix that should address the issue while not breaking the `featuresAt` functionality that code is meant for — let me know if you see that regression again.

**Comment by fnicollet** [comment]
ok, let me try

**Comment by fnicollet** [comment]
ok, it doesn't crash on startup like before but I still get the "prerendered" issue. Think this is related or should I close this one and open another?

**Comment by lbud** [comment]
Yeah, I don't think those are closely enough related to keep this open — can you open a separate ticket for that? Thanks!

**Comment by fnicollet** [comment]
Thanks, for reference the new issue is #915
