### ISSUE TITLE
Complex geometry with holes is displayed wrong (with an extra polygon) on some zoom layers

### ISSUE THREAD

**Issue by mathildor** [mapbox/mapbox-gl-js#9180]
**mapbox-gl-js version**:
https://api.mapbox.com/mapbox-gl-js/v1.6.1/mapbox-gl.js

**browser**:
safari, chrome (probably browser independent)

### Steps to Trigger Behavior

When adding some complex geometries (see fiddle) to the map, the layer is displayed with an extra polygon on some zoom layers. 

Correct display after adding a red see-through layer with a hole:
![image](https://user-images.githubusercontent.com/6861456/72346030-6645b600-36d5-11ea-945d-320ef0036c0f.png)

Zooming out a bit ruins the layer rendering because an extra polygon is displayed covering part of the hole:
![image](https://user-images.githubusercontent.com/6861456/72346055-7b224980-36d5-11ea-99a8-1d331e6012f4.png)

### Link to Demonstration

https://jsfiddle.net/mathildeorstavik/ez5bLhmd/40/

### Expected Behavior
Added layer is displayed similarly on all zoom levels

### Actual Behavior
Layer changes dependent on zoom level

**Comment by mourner** [comment]
This seems to have been fixed by #9214, which will be included in the upcoming release 🎉

**Comment by WebHero0544** [comment]
I still have this problem with the latest version (v3.0.0-Bet.4), I wonder when it will be fixed?
